-- =============================================
-- Cromosol Park Analyzer - Supabase Schema
-- Ejecutar este SQL en el SQL Editor de Supabase
-- =============================================

-- Tabla: parque_automotor
CREATE TABLE IF NOT EXISTS parque_automotor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_modelo INTEGER NOT NULL UNIQUE,
  modelo TEXT NOT NULL,
  modelo2 TEXT,
  marca TEXT NOT NULL,
  desde INTEGER,
  hasta INTEGER,
  clasificacion TEXT,
  parque INTEGER,
  orden INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla: productos
CREATE TABLE IF NOT EXISTS productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stmvid INTEGER NOT NULL,
  nivel1 TEXT NOT NULL,
  nivel2 TEXT,
  proveedor TEXT,
  equivalencia TEXT,
  numero TEXT,
  marca TEXT,
  descripcion TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para mejor performance
CREATE INDEX IF NOT EXISTS idx_productos_stmvid ON productos(stmvid);
CREATE INDEX IF NOT EXISTS idx_productos_nivel1 ON productos(nivel1);
CREATE INDEX IF NOT EXISTS idx_parque_marca ON parque_automotor(marca);
CREATE INDEX IF NOT EXISTS idx_parque_clasificacion ON parque_automotor(clasificacion);

-- =============================================
-- Row Level Security (RLS)
-- =============================================

ALTER TABLE parque_automotor ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;

-- Políticas: usuarios autenticados tienen acceso completo
CREATE POLICY "authenticated_select_parque" ON parque_automotor
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "authenticated_insert_parque" ON parque_automotor
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "authenticated_update_parque" ON parque_automotor
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "authenticated_delete_parque" ON parque_automotor
  FOR DELETE TO authenticated USING (true);

CREATE POLICY "authenticated_select_productos" ON productos
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "authenticated_insert_productos" ON productos
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "authenticated_delete_productos" ON productos
  FOR DELETE TO authenticated USING (true);
